jira:
  url: "https://meridian-t9.atlassian.net"
  email: "alex.aga816@gmail.com"
  # ¡NO pongas el token aquí!

defaults:
  priority: "Medium"
  issue_type_epic: "Epic"
  issue_type_story: "Story"

projects:
  # Alias 't9' para usar en consola
  MERIDIAN:
    key: "MT"  # <--- La CLAVE real de tu proyecto en Jira (ej. PED, T9, CUST)
    epic_name_field: "Epic Name" # Déjalo así por ahora